# version: '3.8'
# services:
#   mongodb:
#     image: mongo:latest
#     container_name: nest_mongo_db
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo_data:/data/db

# volumes:
#   mongo_data:

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: exampledb
    ports:
      - "5432:5432"